#!/bin/bash

$IPT -t nat -I POSTROUTING 1 -s $SUBNET -o $IFACE -j MASQUERADE
$IPT -I INPUT 1 -i $SERVER_NAME -j ACCEPT
$IPT -I FORWARD 1 -i $IFACE -o $SERVER_NAME -j ACCEPT
$IPT -I FORWARD 1 -i $SERVER_NAME -o $IFACE -j ACCEPT
$IPT -I INPUT 1 -i $IFACE -p udp --dport $SERVER_PORT -j ACCEPT

