#!/bin/bash

$IPT -t nat -D POSTROUTING -s $SUBNET -o $IFACE -j MASQUERADE
$IPT -D INPUT -i $SERVER_NAME -j ACCEPT
$IPT -D FORWARD -i $IFACE -o $SERVER_NAME -j ACCEPT
$IPT -D FORWARD -i $SERVER_NAME -o $IFACE -j ACCEPT
$IPT -D INPUT -i $IFACE -p udp --dport $SERVER_PORT -j ACCEPT

